services:
  # Filebeat — collector único varrendo todos os clientes em /usr/share/logs
  filebeat-collector:
    image: docker.elastic.co/beats/filebeat:8.11.1
    user: root
    container_name: filebeat-collector
    networks:
      - kafka-cluster-network
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - ../logs:/usr/share/logs:ro
      - ./filebeat.yml:/config/filebeat.yml:ro
      - filebeat-collector-data:/usr/share/filebeat/data
    command: filebeat -e -c /config/filebeat.yml -strict.perms=false

volumes:
  filebeat-collector-data:

networks:
  kafka-cluster-network:
    external: true
    name: kafka-cluster-network
